apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: db01
  name: db01
spec:
  ports:
  - name: 3306-3306
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: db01
  type: ClusterIP
status:
  loadBalancer: {}
