apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: reb
  name: reb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: reb
    spec:
      containers:
      - image: rabbitmq:latest
        name: rabbitmq
        resources: {}
status: {}
