apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: app
  name: app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: vproapp-port
  selector:
    app: app
  type: ClusterIP
status:
  loadBalancer: {}
