apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: db01
  name: db01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db01
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: db01
    spec:
      containers:
      - image: sai8465/vprodb:latest
        name: vprodb
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: admin
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        resources: {}
status: {}
