apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: db01
  name: db01
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: vprodb-port
  selector:
    app: db01
  type: ClusterIP
status:
  loadBalancer: {}
