apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mem
  name: mem
spec:
  ports:
  - port: 11211
    protocol: TCP
    targetPort: vpromc-port
  selector:
    app: mem
  type: ClusterIP
status:
  loadBalancer: {}
