apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mem
  name: mem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mem
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mem
    spec:
      containers:
      - image: memcached:latest
        name: memcached
        ports:
        - name: vpromc-port
          containerPort: 11211
        resources: {}
status: {}
