apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mem
  name: mem
spec:
  ports:
  - name: 11211-11211
    port: 11211
    protocol: TCP
    targetPort: 11211
  selector:
    app: mem
  type: ClusterIP
status:
  loadBalancer: {}
