apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rab
  name: rab
spec:
  ports:
  - port: 15672
    protocol: TCP
    targetPort: vpromq01-port
  selector:
    app: rab
  type: ClusterIP
status:
  loadBalancer: {}
