name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker: 
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
#       -
#         name: Login to DockerHub
#         uses: docker/login-action@v1
#         with:
#           registry: ghcr.io
#           username: ${{ secrets.DOCKERHUB_USERNAME1 }}
#           password: ${{ secrets.DOCKERHUB_TOKEN1 }}
      -
        name: Login to DockerHub
        uses: shrink/actions-docker-registry-tag@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKERHUB_USERNAME1 }}
          password: ${{ secrets.DOCKERHUB_TOKEN1 }}

      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context:  sai/.
          push: true
          tags: sai8465/git-ci:latest
