name: Build Docker image

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: shrink/actions-docker-registry-tag@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.REPO_OWNER }}
          password: ${{ secrets.GITHUB }}
      - uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          context:  sai/.
          push: true
          tags: ghcr.io/sai8465:latest
